spring:
  application:
    name: ${SPRING_APPLICATION_NAME:codin-user-service}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/codin-user}

server:
  port: ${SERVER_PORT:8082}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_EXPOSE:health,info,metrics}

logging:
  level:
    inu.codin.user: ${LOGGING_LEVEL_USER:DEBUG}
