spring:
  application:
    name: codin-auth-service
  profiles:
    active: ${ENVIRONMENT:local}
  
  # Database Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/codin_auth}
    redis:
      url: ${REDIS_URI:redis://localhost:6379}
      password: ${REDIS_PASSWORD:}

  # Security Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${BASE_URL:http://localhost:8080}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          apple:
            client-id: ${APPLE_CLIENT_ID}
            client-secret: ${APPLE_CLIENT_SECRET}
            redirect-uri: "${BASE_URL:http://localhost:8080}/login/oauth2/code/apple"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - email
              - name
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token

  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      access: ${JWT_ACCESS_EXPIRATION:1800}
      refresh: ${JWT_REFRESH_EXPIRATION:864000}

server:
  port: ${AUTH_SERVICE_PORT:8081}
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:your-secret-key}
  access-token:
    expiration: 3600000  # 1 hour
  refresh-token:
    expiration: 604800000  # 7 days

logging:
  level:
    inu.codin.auth: DEBUG
    org.springframework.security: INFO
