spring:
  application:
    name: ${SPRING_APPLICATION_NAME:codin-chat-service}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/codin-chat}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  port: ${SERVER_PORT:8085}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_EXPOSE:health,info,metrics}

# WebSocket Configuration
websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
  endpoint: ${WEBSOCKET_ENDPOINT:/ws}

logging:
  level:
    inu.codin.chat: ${LOGGING_LEVEL_CHAT:DEBUG}
