server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:codin-api-gateway}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
            allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
            allowed-headers: ${CORS_ALLOWED_HEADERS:*}
            allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:lb://codin-auth-service}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: ${USER_SERVICE_URI:lb://codin-user-service}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: content-service-posts
          uri: ${CONTENT_SERVICE_URI:lb://codin-content-service}
          predicates:
            - Path=/api/posts/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: content-service-comments
          uri: ${CONTENT_SERVICE_URI:lb://codin-content-service}
          predicates:
            - Path=/api/comments/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URI:lb://codin-notification-service}
          predicates:
            - Path=/api/notifications/**,/api/fcm/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: chat-service
          uri: ${CHAT_SERVICE_URI:lb://codin-chat-service}
          predicates:
            - Path=/api/chatroom/**,/api/chats/**
          filters:
            - StripPrefix=1
            - name: Authentication

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_EXPOSE:health,info,metrics}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}

# JWT Configuration for Gateway Authentication Filter
jwt:
  secret: ${JWT_SECRET:your-secret-key}
  expiration: ${JWT_EXPIRATION:86400000}
